#file descriptor:- This is a token generated by the OS that allows programs to do more operations with the file.
#The readline() method reads a single line from the current position, the read() method reads from the current position until the end of the file.
#Both methods read from the current position. The readline() method reads one line, while read() reads until the end of the file.
file1 = open("Interacting with Systems\wordcloud.txt") #accessing file using relative path in Windows
file2 = open("C:\\Users\\bhanu\\Downloads\\wordcloud.txt") #accessing file using absolute path in windows
readsingleline1 = file1.readline() # reads single line from the given text file and each time you call it'll move to next line
readsingleline2 = file1.readline()
content = file1.read() # this reads whole file
print(readsingleline1)
print(readsingleline2)
#print(content)
file1.close() #closes the file

with open("Interacting with Systems\wordcloud.txt") as file: #with open automatically closes the file, but it was used in this block only.
    print(file.readline())


### Iterating through the files ###

with open("Interacting with Systems\wordcloud.txt") as file:
    for line in file:
        print (line.upper()) #file has new line charcter at end of the each line so it'll print extra line b/w the lines

with open("Interacting with Systems\wordcloud.txt") as file:
    for line in file:
        print (line.strip().upper()) # strip() removes new line and prints each line in upper case

with open("Interacting with Systems\wordcloud.txt") as text:
    for line in text:
	    print(line.strip()) #we are iterating line by line, and the strip() command is used to remove extra whitespace.

### Reading file line to the list###

file1 = open("Interacting with Systems\wordcloud.txt")
lines = file1.readlines() # lines variable stores the content of the file
file1.close() # now file is closed
lines.sort() # sorts the content from the lines variable
print(lines) # prints using the \n showing that file has new line in file.

# If file is large, then read it line by line.